server:
  port: 8083

spring:
  application:
    name: parser-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: parser-service
      auto-offset-reset: earliest

elasticsearch:
  uris: ${ES_URL:http://localhost:9200}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.loglens: INFO
